spring:
  application:
    name: myroom
  datasource:
    url: jdbc:h2:mem:myroom;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      encoding: UTF-8
  h2:
    console:
      enabled: true
      path: /h2-console
  messages:
    basename: messages/messages
    encoding: UTF-8
    fallback-to-system-locale: false

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
